FORMAT: 1A

# Group Players

## Players [/players]

### List of all players [GET]

+ Response 200 (application/json)
  {
      "id": 1,
      "name": "Dendi",
      "biography": "",
      "wins": 370,
      "lost": 286,
      "draw": 44,
      "prize_money": 137179,
      "current_team": 5,
      "played_in_teams": [
        {
          "id": 1,
          "name": "navi"
        }
      ]
  }
